In [1]:
import numpy as np

temperature = np.array([25, 28, 31, 35, 38, 27, 33, 40])
print("Original Temperature:")
print(temperature)
# a) Add 2°C to every reading using vectorization

corrected_temperature = temperature + 2
print("\nAfter adding 2°C:")
print(corrected_temperature)


# b) Convert Celsius to Fahrenheit
# Formula: F = (9/5)C + 32

fahrenheit = (9 / 5) * temperature + 32

print("\nTemperature in Fahrenheit:")
print(fahrenheit)


# c) Identify all readings greater than 32°C
# using Boolean indexing

greater_than_32 = temperature[temperature > 32]

print("\nReadings greater than 32°C:")
print(greater_than_32)


# d) Count readings greater than 32°C

count = np.sum(temperature > 32)

print("\nNumber of readings greater than 32°C:")
print(count)


# e) Explanation

print("\nExplanation:")
print("Vectorization performs operations on the entire array without using loops.")
print("Boolean indexing directly selects elements satisfying a condition.")
print("Both methods make NumPy code shorter and more efficient.")

Original Temperature:
[25 28 31 35 38 27 33 40]

After adding 2°C:
[27 30 33 37 40 29 35 42]

Temperature in Fahrenheit:
[ 77.   82.4  87.8  95.  100.4  80.6  91.4 104. ]

Readings greater than 32°C:
[35 38 33 40]

Number of readings greater than 32°C:
4

Explanation:
Vectorization performs operations on the entire array without using loops.
Boolean indexing directly selects elements satisfying a condition.
Both methods make NumPy code shorter and more efficient.


In [2]:
import numpy as np

steps = np.array([
    [5000, 6200, 7100],
    [8000, 7500, 9000],
    [4500, 5100, 4800],
    [9000, 8500, 9500]
])

print("Steps Matrix:")
print(steps)


# a) Calculate total steps recorded

total_steps = np.sum(steps)

print("\nTotal steps:")
print(total_steps)


# b) Calculate mean number of steps

mean_steps = np.mean(steps)

print("\nMean steps:")
print(mean_steps)


# c) Find maximum and minimum values

maximum = np.max(steps)
minimum = np.min(steps)

print("\nMaximum steps:")
print(maximum)

print("\nMinimum steps:")
print(minimum)


# d) Total steps for each day using axis=0

day_total = np.sum(steps, axis=0)

print("\nTotal steps for each day:")
print(day_total)


# e) Total steps for each user using axis=1

user_total = np.sum(steps, axis=1)

print("\nTotal steps for each user:")
print(user_total)


# f) Find user/day position containing maximum value

max_index = np.argmax(steps)

# Convert flat index into row-column position
max_position = np.unravel_index(max_index, steps.shape)

print("\nFlat index of maximum value:")
print(max_index)

print("\nPosition of maximum value (row, column):")
print(max_position)

print("\nMaximum value:")
print(steps[max_position])

Steps Matrix:
[[5000 6200 7100]
 [8000 7500 9000]
 [4500 5100 4800]
 [9000 8500 9500]]

Total steps:
84200

Mean steps:
7016.666666666667

Maximum steps:
9500

Minimum steps:
4500

Total steps for each day:
[26500 27300 30400]

Total steps for each user:
[18300 24500 14400 27000]

Flat index of maximum value:
11

Position of maximum value (row, column):
(np.int64(3), np.int64(2))

Maximum value:
9500


In [3]:
original = np.array([1, 2, 3, 4, 5, 6])

print("Original array:")
print(original)

subset = original[1:5]

print("\nSubset:")
print(subset)

# c) Modify first element of subset to 999

subset[0] = 999

print("\nAfter changing subset[0] to 999:")

print("Subset:")
print(subset)

print("Original:")
print(original)

# d) Create another slice using copy()

copied_array = original[1:5].copy()

copied_array[0] = 500

print("\nAfter modifying copied array:")

print("Copied Array:")
print(copied_array)

print("Original Array:")
print(original)

# e) Create numbers 1 to 12 and reshape to 3 × 4

matrix = np.arange(1, 13).reshape(3, 4)

print("\n3 x 4 Matrix:")
print(matrix)

# f) Indexing and slicing

# First row
first_row = matrix[0, :]

print("\nFirst Row:")
print(first_row)


# Last row
last_row = matrix[-1, :]

print("\nLast Row:")
print(last_row)


# Second column
second_column = matrix[:, 1]

print("\nSecond Column:")
print(second_column)


# Rows 1-2 and Columns 2-3
# Here row/column numbering is treated normally:
# rows 1 and 2 = indices 0,1
# columns 2 and 3 = indices 1,2

selected_elements = matrix[0:2, 1:3]

print("\nRows 1-2 and Columns 2-3:")
print(selected_elements)

# g) flatten() and ravel()


flattened_array = matrix.flatten()

ravelled_array = matrix.ravel()

print("\nArray using flatten():")
print(flattened_array)

print("\nArray using ravel():")
print(ravelled_array)

# h) Modify ravel() result

ravelled_array[0] = 100

print("\nAfter changing ravelled_array[0] to 100:")

print("Ravelled Array:")
print(ravelled_array)

print("Original Matrix:")
print(matrix)

# i) Modify flatten() result

flattened_array[1] = 200

print("\nAfter changing flattened_array[1] to 200:")

print("Flattened Array:")
print(flattened_array)

print("Original Matrix:")
print(matrix)

# j) Display properties

print("\nShape:")
print(matrix.shape)

print("\nNumber of Dimensions:")
print(matrix.ndim)

print("\nSize:")
print(matrix.size)

print("\nData Type:")
print(matrix.dtype)

Original array:
[1 2 3 4 5 6]

Subset:
[2 3 4 5]

After changing subset[0] to 999:
Subset:
[999   3   4   5]
Original:
[  1 999   3   4   5   6]

After modifying copied array:
Copied Array:
[500   3   4   5]
Original Array:
[  1 999   3   4   5   6]

3 x 4 Matrix:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

First Row:
[1 2 3 4]

Last Row:
[ 9 10 11 12]

Second Column:
[ 2  6 10]

Rows 1-2 and Columns 2-3:
[[2 3]
 [6 7]]

Array using flatten():
[ 1  2  3  4  5  6  7  8  9 10 11 12]

Array using ravel():
[ 1  2  3  4  5  6  7  8  9 10 11 12]

After changing ravelled_array[0] to 100:
Ravelled Array:
[100   2   3   4   5   6   7   8   9  10  11  12]
Original Matrix:
[[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]

After changing flattened_array[1] to 200:
Flattened Array:
[  1 200   3   4   5   6   7   8   9  10  11  12]
Original Matrix:
[[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]

Shape:
(3, 4)

Number of Dimensions:
2

Size:
12

Data Type:
int64


In [4]:

X = np.array([
    [6, 70, 3],
    [5, 50, 6],
    [8, 80, 2],
    [4, 30, 8]
], dtype=float)

y = np.array([40, 65, 30, 85], dtype=float)


print("X:")
print(X)

print("\ny:")
print(y)

# a) Display shape and dimensions of X


print("\nShape of X:")
print(X.shape)

print("\nDimensions of X:")
print(X.ndim)

# b) Calculate transpose of X

X_transpose = X.T

print("\nTranspose of X:")
print(X_transpose)

print("\nShape of X.T:")
print(X_transpose.shape)

# c) Calculate X.T @ X

XT_X = X.T @ X

print("\nX.T @ X:")
print(XT_X)

# d) Calculate inverse of X.T @ X

XT_X_inverse = np.linalg.inv(XT_X)

print("\nInverse of X.T @ X:")
print(XT_X_inverse)

# e) Ordinary Least Squares
# beta = (X.T X)^(-1) X.T y

beta = np.linalg.inv(X.T @ X) @ X.T @ y

print("\nOLS Coefficients (beta):")
print(beta)

# f) Meaning of coefficients

print("\nInterpretation:")

print("Beta[0] represents the effect of sleep hours.")
print("Beta[1] represents the effect of activity level.")
print("Beta[2] represents the effect of stress level.")

# g) Prediction for new user

new_user = np.array([5, 40, 7])

predicted_score = new_user @ beta

print("\nNew User:")
print(new_user)

print("\nPredicted Assistance Score:")
print(predicted_score)

X:
[[ 6. 70.  3.]
 [ 5. 50.  6.]
 [ 8. 80.  2.]
 [ 4. 30.  8.]]

y:
[40. 65. 30. 85.]

Shape of X:
(4, 3)

Dimensions of X:
2

Transpose of X:
[[ 6.  5.  8.  4.]
 [70. 50. 80. 30.]
 [ 3.  6.  2.  8.]]

Shape of X.T:
(3, 4)

X.T @ X:
[[  141.  1430.    96.]
 [ 1430. 14700.   910.]
 [   96.   910.   113.]]

Inverse of X.T @ X:
[[ 1.10521428 -0.09848746 -0.14581398]
 [-0.09848746  0.00891203  0.01190129]
 [-0.14581398  0.01190129  0.0368847 ]]

OLS Coefficients (beta):
[-0.15921454  0.14083853 10.06302242]

Interpretation:
Beta[0] represents the effect of sleep hours.
Beta[1] represents the effect of activity level.
Beta[2] represents the effect of stress level.

New User:
[ 5 40  7]

Predicted Assistance Score:
75.27862544779117
