SPARSH KHANDELWAL - 1024170139


In [2]:
import numpy as np
arr = np.array([10, 20, 30, 40, 50])
print("Original array:", arr)
print("After adding 2:", arr + 2)
print("After multiplying by 3:", arr * 3)
print("After dividing by 2:", arr / 2)

Original array: [10 20 30 40 50]
After adding 2: [12 22 32 42 52]
After multiplying by 3: [ 30  60  90 120 150]
After dividing by 2: [ 5. 10. 15. 20. 25.]


In [3]:

arr = np.array([1, 2, 3, 6, 4, 5])
print("Original array:", arr)
reverse_arr = arr[::-1]
print("Reversed array:", reverse_arr)

Original array: [1 2 3 6 4 5]
Reversed array: [5 4 6 3 2 1]


In [5]:
x = np.array([1, 2, 3, 4, 5, 1, 2, 1, 1, 1])
values, counts = np.unique(x, return_counts=True)
max_index = np.argmax(counts)
most_frequent = values[max_index]
indices = np.where(x == most_frequent)[0]
print("Array:", x)
print("Most frequent value:", most_frequent)
print("Frequency:", counts[max_index])
print("Indices:", indices)

Array: [1 2 3 4 5 1 2 1 1 1]
Most frequent value: 1
Frequency: 5
Indices: [0 5 7 8 9]


In [7]:

y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3])

values, counts = np.unique(y, return_counts=True)

max_count = np.max(counts)

most_frequent_values = values[counts == max_count]

print("Most frequent values:", most_frequent_values)
print("Frequency:", max_count)

for value in most_frequent_values:
    indices = np.where(y == value)[0]
    print("Value:", value, "Indices:", indices)

Most frequent values: [1 3]
Frequency: 3
Value: 1 Indices: [0 1 2]
Value: 3 Indices: [4 8 9]


In [8]:
arr = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])

print("1st row, 2nd column:", arr[0, 1])
print("3rd row, 1st column:", arr[2, 0])

1st row, 2nd column: 20
3rd row, 1st column: 70


In [9]:
sparsh = np.linspace(10, 100, 25)
print("Array:")
print(sparsh)
print("Dimensions:", sparsh.ndim)
print("Shape:", sparsh.shape)
print("Total elements:", sparsh.size)
print("Data type:", sparsh.dtype)
print("Total bytes:", sparsh.nbytes)
transpose_sparsh = sparsh.reshape(25, 1)
print("Transpose using reshape():")
print(transpose_sparsh)
print("Transpose using T:")
print(sparsh.T)

Array:
[ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]
Dimensions: 1
Shape: (25,)
Total elements: 25
Data type: float64
Total bytes: 200
Transpose using reshape():
[[ 10.  ]
 [ 13.75]
 [ 17.5 ]
 [ 21.25]
 [ 25.  ]
 [ 28.75]
 [ 32.5 ]
 [ 36.25]
 [ 40.  ]
 [ 43.75]
 [ 47.5 ]
 [ 51.25]
 [ 55.  ]
 [ 58.75]
 [ 62.5 ]
 [ 66.25]
 [ 70.  ]
 [ 73.75]
 [ 77.5 ]
 [ 81.25]
 [ 85.  ]
 [ 88.75]
 [ 92.5 ]
 [ 96.25]
 [100.  ]]
Transpose using T:
[ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]


In [10]:
ucs420_sparsh = np.array([
    [10, 20, 30, 40],
    [50, 60, 70, 80],
    [90, 15, 20, 35]
])
print("Original Array:")
print(ucs420_sparsh)
print("Mean:", np.mean(ucs420_sparsh))
print("Median:", np.median(ucs420_sparsh))
print("Maximum:", np.max(ucs420_sparsh))
print("Minimum:", np.min(ucs420_sparsh))
print("Unique elements:", np.unique(ucs420_sparsh))
reshaped_ucs420_sparsh = ucs420_sparsh.reshape(4, 3)
print("\nReshaped Array:")
print(reshaped_ucs420_sparsh)
resized_ucs420_sparsh = np.resize(ucs420_sparsh, (2, 3))
print("\nResized Array:")
print(resized_ucs420_sparsh)

Original Array:
[[10 20 30 40]
 [50 60 70 80]
 [90 15 20 35]]
Mean: 43.333333333333336
Median: 37.5
Maximum: 90
Minimum: 10
Unique elements: [10 15 20 30 35 40 50 60 70 80 90]

Reshaped Array:
[[10 20 30]
 [40 50 60]
 [70 80 90]
 [15 20 35]]

Resized Array:
[[10 20 30]
 [40 50 60]]
