In [1]:
!unzip "*.zip"

Archive:  archive.zip
  inflating: AWCustomers.csv         
  inflating: AWSales.csv             
  inflating: AWTest-Classification.csv  
  inflating: AWTest-Regression.csv   


In [2]:
import pandas as pd

customers = pd.read_csv("AWCustomers.csv")

customers.head()

,CustomerID,Title,FirstName,MiddleName,LastName,Suffix,AddressLine1,AddressLine2,City,StateProvinceName,...,Education,Occupation,Gender,MaritalStatus,HomeOwnerFlag,NumberCarsOwned,NumberChildrenAtHome,TotalChildren,YearlyIncome,LastUpdated
0,21173,NaN,Chad,C,Yuan,NaN,7090 C. Mount Hood,NaN,Wollongong,New South Wales,...,Bachelors,Clerical,M,M,1,3,0,1,81916,2017-03-06
1,13249,NaN,Ryan,NaN,Perry,NaN,3651 Willow Lake Rd,NaN,Shawnee,British Columbia,...,Partial College,Clerical,M,M,1,2,1,2,81076,2017-03-06
2,29350,NaN,Julia,NaN,Thompson,NaN,1774 Tice Valley Blvd.,NaN,West Covina,California,...,Bachelors,Clerical,F,S,0,3,0,0,86387,2017-03-06
3,13503,NaN,Theodore,NaN,Gomez,NaN,2103 Baldwin Dr,NaN,Liverpool,England,...,Partial College,Skilled Manual,M,M,1,2,1,2,61481,2017-03-06
4,22803,NaN,Marshall,J,Shan,NaN,Am Gallberg 234,NaN,Werne,Nordrhein-Westfalen,...,Partial College,Skilled Manual,M,S,1,1,0,0,51804,2017-03-06


In [3]:
classification = pd.read_csv("AWTest-Classification.csv")

classification.head()

,CustomerID,Title,FirstName,MiddleName,LastName,Suffix,AddressLine1,AddressLine2,City,StateProvinceName,...,Education,Occupation,Gender,MaritalStatus,HomeOwnerFlag,NumberCarsOwned,NumberChildrenAtHome,TotalChildren,YearlyIncome,LastUpdated
0,11219,NaN,Charles,NaN,Cook,NaN,6871 Bel Air Dr.,NaN,Woodburn,Oregon,...,High School,Skilled Manual,M,M,1,2,2,2,56100,2017-03-06
1,11241,NaN,Lisa,NaN,Cai,NaN,"102, rue de Berri",NaN,Les Ulis,Essonne,...,Partial College,Skilled Manual,F,S,1,0,0,0,61555,2017-03-06
2,11352,NaN,Raymond,A,Rodriguez,NaN,"24, impasse Ste-Madeleine",NaN,Pantin,Seine Saint Denis,...,Partial College,Clerical,M,M,1,3,0,2,83613,2017-03-06
3,11904,NaN,Kaylee,NaN,Cook,NaN,5742 Curtis Drive,NaN,Geelong,Victoria,...,Graduate Degree,Professional,F,S,1,2,0,0,130551,2017-03-06
4,11908,NaN,Rafael,A,Tang,NaN,8839 Leonard Dr,NaN,South Melbourne,Victoria,...,Graduate Degree,Professional,M,S,1,2,0,0,135915,2017-03-06


In [4]:
sales = pd.read_csv("AWSales.csv")

sales.head()

,CustomerID,BikeBuyer,AvgMonthSpend
0,21173,1,50.97
1,13249,1,53.11
2,29350,1,54.08
3,13503,1,56.93
4,22803,1,55.41


In [5]:
regression = pd.read_csv("AWTest-Regression.csv")

regression.head()

,CustomerID,Title,FirstName,MiddleName,LastName,Suffix,AddressLine1,AddressLine2,City,StateProvinceName,...,Education,Occupation,Gender,MaritalStatus,HomeOwnerFlag,NumberCarsOwned,NumberChildrenAtHome,TotalChildren,YearlyIncome,LastUpdated
0,11908,NaN,Rafael,A,Tang,NaN,8839 Leonard Dr,NaN,South Melbourne,Victoria,...,Graduate Degree,Professional,M,S,1,2,0,0,135915,2017-03-06
1,12286,NaN,Nathan,M,Jenkins,NaN,3093 Roland Drive,NaN,Peterborough,England,...,Graduate Degree,Professional,M,S,1,2,0,0,137732,2017-03-06
2,12892,NaN,Brian,NaN,Peterson,NaN,1284 Poppy Pl.,NaN,Royal Oak,British Columbia,...,Graduate Degree,Professional,M,M,1,2,0,0,135404,2017-03-06
3,14698,NaN,Diane,NaN,Navarro,NaN,Potsdamer Straße 92324,NaN,Frankfurt am Main,Saarland,...,Bachelors,Management,F,M,1,3,0,0,104040,2017-03-06
4,15085,NaN,Kristin,H,Jai,NaN,"88, impasse Notre-Dame",NaN,Morangis,Essonne,...,Graduate Degree,Professional,F,S,1,0,0,0,129319,2017-03-06


To perform important data manipulation and analysis operations using NumPy and Pandas on the Microsoft Adventure Works customer dataset.

In [6]:
import numpy as np
import pandas as pd

In [7]:
df = pd.read_csv("AWCustomers.csv")

In [8]:
df.head()

,CustomerID,Title,FirstName,MiddleName,LastName,Suffix,AddressLine1,AddressLine2,City,StateProvinceName,...,Education,Occupation,Gender,MaritalStatus,HomeOwnerFlag,NumberCarsOwned,NumberChildrenAtHome,TotalChildren,YearlyIncome,LastUpdated
0,21173,NaN,Chad,C,Yuan,NaN,7090 C. Mount Hood,NaN,Wollongong,New South Wales,...,Bachelors,Clerical,M,M,1,3,0,1,81916,2017-03-06
1,13249,NaN,Ryan,NaN,Perry,NaN,3651 Willow Lake Rd,NaN,Shawnee,British Columbia,...,Partial College,Clerical,M,M,1,2,1,2,81076,2017-03-06
2,29350,NaN,Julia,NaN,Thompson,NaN,1774 Tice Valley Blvd.,NaN,West Covina,California,...,Bachelors,Clerical,F,S,0,3,0,0,86387,2017-03-06
3,13503,NaN,Theodore,NaN,Gomez,NaN,2103 Baldwin Dr,NaN,Liverpool,England,...,Partial College,Skilled Manual,M,M,1,2,1,2,61481,2017-03-06
4,22803,NaN,Marshall,J,Shan,NaN,Am Gallberg 234,NaN,Werne,Nordrhein-Westfalen,...,Partial College,Skilled Manual,M,S,1,1,0,0,51804,2017-03-06


In [9]:
df.shape

(18361, 24)

In [10]:
df.columns

Index(['CustomerID', 'Title', 'FirstName', 'MiddleName', 'LastName', 'Suffix',
       'AddressLine1', 'AddressLine2', 'City', 'StateProvinceName',
       'CountryRegionName', 'PostalCode', 'PhoneNumber', 'BirthDate',
       'Education', 'Occupation', 'Gender', 'MaritalStatus', 'HomeOwnerFlag',
       'NumberCarsOwned', 'NumberChildrenAtHome', 'TotalChildren',
       'YearlyIncome', 'LastUpdated'],
      dtype='object')

In [11]:
df.dtypes

,0
CustomerID,int64
Title,object
FirstName,object
MiddleName,object
LastName,object
Suffix,object
AddressLine1,object
AddressLine2,object
City,object
StateProvinceName,object


In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18361 entries, 0 to 18360
Data columns (total 24 columns):
 #   Column                Non-Null Count  Dtype 
---  ------                --------------  ----- 
 0   CustomerID            18361 non-null  int64 
 1   Title                 101 non-null    object
 2   FirstName             18361 non-null  object
 3   MiddleName            10572 non-null  object
 4   LastName              18361 non-null  object
 5   Suffix                3 non-null      object
 6   AddressLine1          18361 non-null  object
 7   AddressLine2          311 non-null    object
 8   City                  18361 non-null  object
 9   StateProvinceName     18361 non-null  object
 10  CountryRegionName     18361 non-null  object
 11  PostalCode            18361 non-null  object
 12  PhoneNumber           18361 non-null  object
 13  BirthDate             18361 non-null  object
 14  Education             18361 non-null  object
 15  Occupation            18361 non-null

In [13]:
df.describe()

,CustomerID,HomeOwnerFlag,NumberCarsOwned,NumberChildrenAtHome,TotalChildren,YearlyIncome
count,18361.000000,18361.000000,18361.000000,18361.000000,18361.000000,18361.000000
mean,20241.987092,0.610588,1.270301,0.338162,0.850389,72754.779642
std,5336.332731,0.487630,0.913989,0.568957,0.927315,30686.014313
min,11000.000000,0.000000,0.000000,0.000000,0.000000,25435.000000
25%,15621.000000,0.000000,1.000000,0.000000,0.000000,53312.000000
50%,20248.000000,1.000000,1.000000,0.000000,0.000000,61851.000000
75%,24863.000000,1.000000,2.000000,1.000000,2.000000,87410.000000
max,29483.000000,1.000000,5.000000,3.000000,3.000000,139115.000000


In [14]:
df["FirstName"]

,FirstName
0,Chad
1,Ryan
2,Julia
3,Theodore
4,Marshall
...,...
18356,Grace
18357,Tasha
18358,Jaclyn
18359,Erin


In [15]:
df.iloc[0]

,0
CustomerID,21173
Title,NaN
FirstName,Chad
MiddleName,C
LastName,Yuan
Suffix,NaN
AddressLine1,7090 C. Mount Hood
AddressLine2,NaN
City,Wollongong
StateProvinceName,New South Wales


In [16]:
df.iloc[0:5]

,CustomerID,Title,FirstName,MiddleName,LastName,Suffix,AddressLine1,AddressLine2,City,StateProvinceName,...,Education,Occupation,Gender,MaritalStatus,HomeOwnerFlag,NumberCarsOwned,NumberChildrenAtHome,TotalChildren,YearlyIncome,LastUpdated
0,21173,NaN,Chad,C,Yuan,NaN,7090 C. Mount Hood,NaN,Wollongong,New South Wales,...,Bachelors,Clerical,M,M,1,3,0,1,81916,2017-03-06
1,13249,NaN,Ryan,NaN,Perry,NaN,3651 Willow Lake Rd,NaN,Shawnee,British Columbia,...,Partial College,Clerical,M,M,1,2,1,2,81076,2017-03-06
2,29350,NaN,Julia,NaN,Thompson,NaN,1774 Tice Valley Blvd.,NaN,West Covina,California,...,Bachelors,Clerical,F,S,0,3,0,0,86387,2017-03-06
3,13503,NaN,Theodore,NaN,Gomez,NaN,2103 Baldwin Dr,NaN,Liverpool,England,...,Partial College,Skilled Manual,M,M,1,2,1,2,61481,2017-03-06
4,22803,NaN,Marshall,J,Shan,NaN,Am Gallberg 234,NaN,Werne,Nordrhein-Westfalen,...,Partial College,Skilled Manual,M,S,1,1,0,0,51804,2017-03-06


In [17]:
df.loc[0]

,0
CustomerID,21173
Title,NaN
FirstName,Chad
MiddleName,C
LastName,Yuan
Suffix,NaN
AddressLine1,7090 C. Mount Hood
AddressLine2,NaN
City,Wollongong
StateProvinceName,New South Wales


In [18]:
df[df["Gender"] == "M"]

,CustomerID,Title,FirstName,MiddleName,LastName,Suffix,AddressLine1,AddressLine2,City,StateProvinceName,...,Education,Occupation,Gender,MaritalStatus,HomeOwnerFlag,NumberCarsOwned,NumberChildrenAtHome,TotalChildren,YearlyIncome,LastUpdated
0,21173,NaN,Chad,C,Yuan,NaN,7090 C. Mount Hood,NaN,Wollongong,New South Wales,...,Bachelors,Clerical,M,M,1,3,0,1,81916,2017-03-06
1,13249,NaN,Ryan,NaN,Perry,NaN,3651 Willow Lake Rd,NaN,Shawnee,British Columbia,...,Partial College,Clerical,M,M,1,2,1,2,81076,2017-03-06
3,13503,NaN,Theodore,NaN,Gomez,NaN,2103 Baldwin Dr,NaN,Liverpool,England,...,Partial College,Skilled Manual,M,M,1,2,1,2,61481,2017-03-06
4,22803,NaN,Marshall,J,Shan,NaN,Am Gallberg 234,NaN,Werne,Nordrhein-Westfalen,...,Partial College,Skilled Manual,M,S,1,1,0,0,51804,2017-03-06
6,11229,NaN,Adrian,C,Stewart,NaN,6898 Shaw Rd.,NaN,Redwood City,California,...,Partial College,Manual,M,S,1,1,0,0,34919,2017-03-06
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18343,29310,NaN,Armando,NaN,Gutierrez,NaN,8364 Encinal Place,NaN,Bendigo,Victoria,...,Bachelors,Clerical,M,S,0,3,0,0,79017,2017-03-06
18347,29064,NaN,Jose,NaN,Butler,NaN,2109 Harvey Way,NaN,Cranbourne,Victoria,...,Partial College,Clerical,M,S,1,2,0,1,87541,2017-03-06
18348,11287,NaN,Henry,B,Garcia,NaN,3268 Hazelwood Lane,NaN,Cliffside,British Columbia,...,Partial College,Skilled Manual,M,M,1,2,0,1,57863,2017-03-06
18349,11465,NaN,Louis,NaN,Luo,NaN,4187 Banbury Loop,NaN,Gold Coast,Queensland,...,Bachelors,Clerical,M,M,1,1,1,1,85747,2017-03-06


In [19]:
df[df["YearlyIncome"] > 50000]

,CustomerID,Title,FirstName,MiddleName,LastName,Suffix,AddressLine1,AddressLine2,City,StateProvinceName,...,Education,Occupation,Gender,MaritalStatus,HomeOwnerFlag,NumberCarsOwned,NumberChildrenAtHome,TotalChildren,YearlyIncome,LastUpdated
0,21173,NaN,Chad,C,Yuan,NaN,7090 C. Mount Hood,NaN,Wollongong,New South Wales,...,Bachelors,Clerical,M,M,1,3,0,1,81916,2017-03-06
1,13249,NaN,Ryan,NaN,Perry,NaN,3651 Willow Lake Rd,NaN,Shawnee,British Columbia,...,Partial College,Clerical,M,M,1,2,1,2,81076,2017-03-06
2,29350,NaN,Julia,NaN,Thompson,NaN,1774 Tice Valley Blvd.,NaN,West Covina,California,...,Bachelors,Clerical,F,S,0,3,0,0,86387,2017-03-06
3,13503,NaN,Theodore,NaN,Gomez,NaN,2103 Baldwin Dr,NaN,Liverpool,England,...,Partial College,Skilled Manual,M,M,1,2,1,2,61481,2017-03-06
4,22803,NaN,Marshall,J,Shan,NaN,Am Gallberg 234,NaN,Werne,Nordrhein-Westfalen,...,Partial College,Skilled Manual,M,S,1,1,0,0,51804,2017-03-06
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18356,25414,NaN,Grace,C,Bailey,NaN,6627 Camelback Ct.,NaN,Coronado,California,...,Graduate Degree,Skilled Manual,F,M,0,1,0,2,52953,2017-03-06
18357,11459,NaN,Tasha,NaN,Deng,NaN,9627 Kendall Rd,NaN,Port Macquarie,New South Wales,...,Bachelors,Skilled Manual,F,S,0,2,0,0,60992,2017-03-06
18358,12160,NaN,Jaclyn,NaN,Zhang,NaN,4364 Viera Avenue,NaN,Beaverton,Oregon,...,Partial College,Skilled Manual,F,S,0,2,0,0,51859,2017-03-06
18359,14353,NaN,Erin,I,Reed,NaN,3866 Mt. Everest Court,NaN,Vancouver,British Columbia,...,High School,Clerical,F,S,0,0,0,0,87177,2017-03-06


In [20]:
df.sort_values("YearlyIncome")

,CustomerID,Title,FirstName,MiddleName,LastName,Suffix,AddressLine1,AddressLine2,City,StateProvinceName,...,Education,Occupation,Gender,MaritalStatus,HomeOwnerFlag,NumberCarsOwned,NumberChildrenAtHome,TotalChildren,YearlyIncome,LastUpdated
7539,25367,NaN,Abigail,NaN,Torres,NaN,682 Ambush Dr..,NaN,Shawnee,British Columbia,...,Partial College,Manual,F,M,1,1,2,2,25435,2017-03-06
2088,17096,NaN,Samantha,S,Bennett,NaN,Hauptstr 2929,NaN,Hof,Bayern,...,Partial High School,Manual,F,M,0,0,0,1,25445,2017-03-06
4355,29302,NaN,Carolyn,S,Fernandez,NaN,5639 Lee Lane,NaN,Geelong,Victoria,...,Bachelors,Manual,F,S,0,1,0,0,25449,2017-03-06
6963,24613,NaN,Stacy,NaN,Serrano,NaN,1745 Chickpea Ct,NaN,Melton,Victoria,...,Partial High School,Manual,F,M,0,0,0,1,25467,2017-03-06
17743,27337,NaN,Julia,R,Hall,NaN,9995 Altura Drive,NaN,Watford,England,...,Partial High School,Manual,F,M,1,1,1,2,25469,2017-03-06
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10185,22052,NaN,Zachary,NaN,Butler,NaN,4050 Canyon Road,NaN,Bellflower,California,...,Graduate Degree,Professional,M,M,1,3,0,0,139071,2017-03-06
10577,13560,NaN,Andres,T,Shan,NaN,Im Himmelsweg 89,NaN,Frankfurt am Main,Saarland,...,Graduate Degree,Professional,M,M,1,2,1,2,139082,2017-03-06
9525,20303,NaN,Bryce,J,Morgan,NaN,1509 Orangewood Ave.,NaN,Colma,California,...,Graduate Degree,Professional,M,M,1,3,0,0,139099,2017-03-06
16892,17466,NaN,Thomas,NaN,Perez,NaN,27 Elkwood Dr.,NaN,Lebanon,Oregon,...,Graduate Degree,Professional,M,M,1,2,0,3,139109,2017-03-06


mathematical function

In [21]:
df["YearlyIncome"].mean()

np.float64(72754.77964163171)

In [22]:
df["YearlyIncome"].median()

61851.0

In [23]:
df.groupby("Gender")["YearlyIncome"].mean()

,YearlyIncome
Gender,
F,72765.783117
M,72744.028535


numpy

In [24]:
arr = np.array([10, 20, 30, 40, 50])

print(arr)

[10 20 30 40 50]


In [25]:
print(arr.ndim)
print(arr.shape)
print(arr.size)
print(arr.dtype)

1
(5,)
5
int64


In [26]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [27]:
arr[0]

np.int64(10)

In [28]:
arr[1:4]

array([20, 30, 40])

In [29]:
np.sort(arr)

array([10, 20, 30, 40, 50])

In [30]:
arr2 = np.array([10, 20, 20, 30, 30, 30, 40])

np.unique(arr2)

array([10, 20, 30, 40])

In [31]:
np.where(arr > 25, "High", "Low")

array(['Low', 'Low', 'High', 'High', 'High'], dtype='<U4')

In [32]:
print("Dataset Shape:", df.shape)
print("Number of Columns:", len(df.columns))
print("Number of Rows:", len(df))
print("Missing Values:", df.isnull().sum().sum())

Dataset Shape: (18361, 24)
Number of Columns: 24
Number of Rows: 18361
Missing Values: 62457
